export const CREATE_ADVERT = 'CREATE_ADVERT';
export const CREATE_ADVERT_ERROR = 'CREATE_ADVERT_ERROR';
export const REMOVE_ADVERT = 'REMOVE_ADVERT';
export const REMOVE_ADVERT_ERROR = 'REMOVE_ADVERT_ERROR';
export const UPDATE_ADVERT = 'UPDATE_ADVERT';
export const UPDATE_ADVERT_ERROR = 'UPDATE_ADVERT_ERROR';
export const UPDATE_VIEWS_ADVERT = 'UPDATE_VIEWS_ADVERT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SEARCH = 'SEARCH';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const DELETE_USER_DB = 'DELETE_USER_DB';
export const DELETE_USER_DB_ERROR = 'DELETE_USER_DB_ERROR';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_PASSWORD_ERROR = 'UPDATE_USER_PASSWORD_ERROR';
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';
export const UPDATE_USER_EMAIL_ERROR = 'UPDATE_USER_EMAIL_ERROR';
